wandb_version: 1

beta1:
  value: 0.9
beta2:
  value: 0.999
bottleneck_units:
  value: 64
bottleneck_units_tf:
  value: 64
conv_channel_list:
  value:
  - 96
  - 96
  - 112
  - 112
  - 128
  - 128
conv_filter_size_1_atac:
  value: 15
conv_filter_size_1_seq:
  value: 15
conv_filter_size_2_atac:
  value: 5
conv_filter_size_2_seq:
  value: 5
dim:
  value: 64
dropout:
  value: 0.2
epsilon:
  value: 1.0e-10
fft_prior_scale:
  value: 0.5
freq_limit:
  value: 5000
gradient_clip:
  value: 0.2
hidden_size:
  value: 256
input_length:
  value: 16384
kernel_regularizer:
  value: 1.0e-05
kernel_transformation:
  value: softmax_kernel_transformation
lr_base:
  value: 5.0e-05
min_lr:
  value: 5.0e-10
momentum:
  value: 0.9
num_heads:
  value: 4
num_random_features:
  value: 256
num_transformer_layers:
  value: 2
optimizer:
  value: adamw
organisms:
  value: hg
precision:
  value: mixed_bfloat16
rectify:
  value: 'True'
rel_pos_bins:
  value: 512
use_fft_prior:
  value: true
use_tf_acc:
  value: true
weight_decay_frac:
  value: 0.01
