wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1661178895.775469
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.7.10
      5: 0.13.1
      8:
      - 5
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
bottleneck_units:
  desc: null
  value: 32
bottleneck_units_tf:
  desc: null
  value: 32
conv_channel_list:
  desc: null
  value:
  - 48
  - 48
  - 56
  - 56
  - 64
  - 64
conv_filter_size_1_atac:
  desc: null
  value: 15
conv_filter_size_1_seq:
  desc: null
  value: 15
conv_filter_size_2_atac:
  desc: null
  value: 5
conv_filter_size_2_seq:
  desc: null
  value: 5
dim:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.25
epsilon:
  desc: null
  value: 1.0e-10
fft_prior_scale:
  desc: null
  value: 0.2
freq_limit_scale:
  desc: null
  value: 0.07
gradient_clip:
  desc: null
  value: 0.2
hidden_size:
  desc: null
  value: 128
input_length:
  desc: null
  value: 16384
kernel_regularizer:
  desc: null
  value: 1.0e-05
kernel_transformation:
  desc: null
  value: relu_kernel_transformation,softmax_kernel_transformation
lr_base:
  desc: null
  value: 5.0e-05
min_lr:
  desc: null
  value: 5.0e-12
momentum:
  desc: null
  value: 0.9
num_heads:
  desc: null
  value: 4
num_random_features:
  desc: null
  value: 128
num_transformer_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adamw
organisms:
  desc: null
  value: hg
precision:
  desc: null
  value: mixed_bfloat16
rectify:
  desc: null
  value: 'True'
rel_pos_bins:
  desc: null
  value: 512
use_fft_prior:
  desc: null
  value: true
use_tf_acc:
  desc: null
  value: true
weight_decay_frac:
  desc: null
  value: 0.01
