#!/bin/bash -l

python3 train_model_batchnorm_experiments.py \
            --tpu_name="node-6" \
            --tpu_zone="us-central1-a" \
            --wandb_project="enformer_baseline" \
            --wandb_user="njaved" \
            --wandb_sweep_name="enformer_baseline" \
            --gcs_project="picard-testing-176520" \
            --gcs_path="gs://picard-testing-176520/genformer_baseline/tfrecords" \
            --gcs_path_TSS="gs://picard-testing-176520/genformer_baseline/tss_centered/tfrecords" \
            --num_epochs=100 \
            --warmup_frac=0.02 \
            --patience=50\
            --min_delta=0.00001 \
            --model_save_dir="gs://picard-testing-176520/enformer_performer_baseline/models" \
            --model_save_basename="enformer_performer_baseline_230123" \
            --lr_base1="1.0e-06" \
            --lr_base2="1.0e-04" \
            --wd_1="0.0" \
            --wd_2="0.0" \
            --decay_frac="1.0" \
            --gradient_clip="1.0" \
            --BN_momentum="0.90" \
            --post_BN_dropout_rate="0.00" \
            --epsilon=1.0e-8 \
            --num_parallel=8 \
            --dropout_rate=0.40 \
            --attention_dropout_rate=0.05 \
            --savefreq=5 \
            --val_examples_TSS=2134 \
            --load_init="False" \
            --freeze_conv_layers="False" \
            --num_examples_dict="human:34021,2213" \
            --num_transformer_layers=6 \
            --num_heads=4 \
            --stable_variant="False" \
            --optimizer="adamw" \
            --heads_channels="human:98" \
            --kernel_transformation="relu_kernel_transformation" \
            --enformer_checkpoint_path="sonnet_weights" \
            --use_enf_conv_block="True" \
            --use_LN_only="False"
            
