wandb_version: 1

BN_momentum:
  value: 0.9
attention_dropout_rate:
  value: 0.05
decay_frac:
  value: 0.9
dropout_rate:
  value: 0.4
epsilon:
  value: 1.0e-08
filter_list_seq:
  value:
  - 768
  - 896
  - 1024
  - 1152
  - 1280
  - 1536
freeze_conv_layers:
  value: false
gradient_clip:
  value: 1
heads_channels:
  value:
    human: 5313
    mouse: 1643
hidden_size:
  value: 1552
input_length:
  value: 196608
kernel_transformation:
  value: relu_kernel_transformation
load_init:
  value: true
lr_base1:
  value: 1.0e-06
lr_base2:
  value: 0.0001
nb_random_features:
  value: 256
norm:
  value: true
normalize:
  value: true
num_heads:
  value: 8
num_transformer_layers:
  value: 6
optimizer:
  value: adamw
output_length:
  value: 1536
use_mask_pos:
  value: false
use_rot_emb:
  value: true
wd_1:
  value: 1.0e-08
wd_2:
  value: 1.0e-06
