wandb_version: 1

BN_momentum:
  desc: null
  value: 0.9
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1678295904.544779
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 19
      - 23
      - 37
      4: 3.7.10
      5: 0.13.1
      8:
      - 5
atac_mask_dropout:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 4
cage_scale:
  desc: null
  value: 0.5
crop_size:
  desc: null
  value: 100
decay_frac:
  desc: null
  value: 1
dropout_rate:
  desc: null
  value: 0.05
epsilon:
  desc: null
  value: 1.0e-08
filter_list_atac:
  desc: null
  value:
  - 32
  - 64
filter_list_seq:
  desc: null
  value:
  - 768
  - 896
  - 1024
  - 1152
  - 1280
  - 1536
final_output_length:
  desc: null
  value: 312
freeze_conv_layers:
  desc: null
  value: true
gcs_path:
  desc: null
  value: gs://picard-testing-176520/genformer_atac_rampage_globalacc_conv_rpgc_5prime_65k
gcs_path_TSS:
  desc: null
  value: gs://picard-testing-176520/genformer_atac_rampage_globalacc_conv_rpgc_TSS_5prime_65k
gcs_path_TSS_holdout:
  desc: null
  value: gs://picard-testing-176520/genformer_atac_rampage_globalacc_conv_rpgc_TSS_5prime_65k_holdout
gcs_path_holdout:
  desc: null
  value: gs://picard-testing-176520/genformer_atac_rampage_globalacc_conv_rpgc_5prime_65k_holdout
global_acc_size:
  desc: null
  value: 128
gradient_clip:
  desc: null
  value: 5
inits_type:
  desc: null
  value: enformer_conv
input_length:
  desc: null
  value: 65536
kernel_transformation:
  desc: null
  value: relu_kernel_transformation
learnable_PE:
  desc: null
  value: true
load_init:
  desc: null
  value: true
log_atac:
  desc: null
  value: true
loss_fn:
  desc: null
  value: poisson
lr_base:
  desc: null
  value: 0.01
lr_base1:
  desc: null
  value: 5.0e-06
lr_base2:
  desc: null
  value: 0.0001
max_shift:
  desc: null
  value: 10
min_delta:
  desc: null
  value: 5.0e-06
model_save_basename:
  desc: null
  value: aformer_baseline
model_save_dir:
  desc: null
  value: gs://picard-testing-176520/paired_rampage_atac/genformer/models
num_epochs:
  desc: null
  value: 100
num_heads:
  desc: null
  value: 4
num_random_features:
  desc: null
  value: 256
num_transformer_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adamw
output_length:
  desc: null
  value: 512
output_length_ATAC:
  desc: null
  value: 16384
output_res:
  desc: null
  value: 128
patience:
  desc: null
  value: 50
pointwise_dropout_rate:
  desc: null
  value: 0.1
predict_masked_atac_bool:
  desc: null
  value: true
rectify:
  desc: null
  value: true
sonnet_weights_bool:
  desc: null
  value: true
stable_variant:
  desc: null
  value: false
total_steps:
  desc: null
  value: 31
tpu:
  desc: null
  value: node-8
train_examples:
  desc: null
  value: 1000
train_steps:
  desc: null
  value: 31
use_atac:
  desc: null
  value: true
use_global_acc:
  desc: null
  value: true
val_examples:
  desc: null
  value: 150
val_examples_TSS:
  desc: null
  value: 150
val_examples_TSS_ho:
  desc: null
  value: 150
val_examples_ho:
  desc: null
  value: 150
val_steps:
  desc: null
  value: 4
val_steps_TSS:
  desc: null
  value: 4
val_steps_TSS_ho:
  desc: null
  value: 4
val_steps_ho:
  desc: null
  value: 4
warmup_frac:
  desc: null
  value: 0.005
wd_1_frac:
  desc: null
  value: 0.001
wd_2_frac:
  desc: null
  value: 0.01
