wandb_version: 1

BN_momentum:
  value: 0.9
atac_corrupt_rate:
  value: 20
atac_mask_dropout:
  value: 0.15
bce_loss_scale:
  value: 0.95
decay_frac:
  value: 0.5
dropout_rate:
  value: 0.2
epsilon:
  value: 1.0e-08
filter_list_atac:
  value:
  - 64
  - 128
filter_list_seq:
  value:
  - 512
  - 564
  - 616
  - 668
  - 720
  - 768
final_output_length:
  value: 2048
final_point_scale:
  value: 4
freeze_conv_layers:
  value: false
gradient_clip:
  value: 2.5
input_length:
  value: 524288
kernel_transformation:
  value: relu_kernel_transformation
learnable_PE:
  value: false
load_init:
  value: false
log_atac:
  value: true
lr_base1:
  value: 0.0002
lr_base2:
  value: 0.0002
num_heads:
  value: 8
num_random_features:
  value: 256
num_transformer_layers:
  value: 7
optimizer:
  value: adam
output_length:
  value: 4096
output_length_ATAC:
  value: 131072
output_res:
  value: 128
pointwise_dropout_rate:
  value: 0.1
random_mask_size:
  value: 768
rectify:
  value: true
seed:
  value: 12
seq_corrupt_rate:
  value: 15
sonnet_weights_bool:
  value: false
stable_variant:
  value: false
use_atac:
  value: true
use_pooling:
  value: 'False'
use_seq:
  value: true
wd_1:
  value: 0.001
wd_2:
  value: 0.001
