wandb_version: 1

BN_momentum:
  desc: null
  value: 0.9
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1674749406.426134
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 19
      - 23
      - 37
      4: 3.7.10
      5: 0.13.1
      8:
      - 5
attention_dropout_rate:
  desc: null
  value: 0.05
batch_size:
  desc: null
  value: 1
crop_size:
  desc: null
  value: 320
decay_frac:
  desc: null
  value: 1
dropout_rate:
  desc: null
  value: 0.4
epsilon:
  desc: null
  value: 1.0e-08
filter_list_seq:
  desc: null
  value:
  - 768
  - 896
  - 1024
  - 1152
  - 1280
  - 1536
final_output_length:
  desc: null
  value: 896
freeze_conv_layers:
  desc: null
  value: false
gcs_path:
  desc: null
  value: gs://picard-testing-176520/enformer_baseline_paired_ATAC_RAMPAGE/tfrecords
gcs_path_TSS:
  desc: null
  value: gs://picard-testing-176520/enformer_baseline_paired_ATAC_RAMPAGE/tss_sequences/tfrecords
gradient_clip:
  desc: null
  value: 1
hidden_size:
  desc: null
  value: 1552
inits_type:
  desc: null
  value: enformer_conv
input_length:
  desc: null
  value: 196608
kernel_transformation:
  desc: null
  value: relu_kernel_transformation
load_init:
  desc: null
  value: false
lr_base:
  desc: null
  value: 0.01
lr_base1:
  desc: null
  value: 1.0e-06
lr_base2:
  desc: null
  value: 0.0001
max_shift:
  desc: null
  value: 10
min_delta:
  desc: null
  value: 1.0e-05
model_save_basename:
  desc: null
  value: enformer_performer_baseline_atac_mean_pretrain
model_save_dir:
  desc: null
  value: gs://picard-testing-176520/enformer_performer_baseline_atac_mean_pretrain/models
nb_random_features:
  desc: null
  value: 256
norm:
  desc: null
  value: true
normalize:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 100
num_heads:
  desc: null
  value: 8
num_transformer_layers:
  desc: null
  value: 6
optimizer:
  desc: null
  value: adamw
output_length:
  desc: null
  value: 1536
output_res:
  desc: null
  value: 128
patience:
  desc: null
  value: 50
total_steps:
  desc: null
  value: 62
tpu:
  desc: null
  value: node-6
train_examples:
  desc: null
  value: 500
train_steps:
  desc: null
  value: 62
use_mask_pos:
  desc: null
  value: false
use_rot_emb:
  desc: null
  value: true
val_examples:
  desc: null
  value: 500
val_examples_TSS:
  desc: null
  value: 500
val_steps:
  desc: null
  value: 62
val_steps_TSS:
  desc: null
  value: 62
warmup_frac:
  desc: null
  value: 0.02
wd_1:
  desc: null
  value: 0
wd_2:
  desc: null
  value: 0
