wandb_version: 1

BN_momentum:
  value: 0.9
atac_mask_dropout:
  value: 0.1
cage_scale:
  value: 0.5
decay_frac:
  value: 1
dropout_rate:
  value: 0.05
epsilon:
  value: 1.0e-08
filter_list_atac:
  value:
  - 32
  - 64
filter_list_seq:
  value:
  - 768
  - 896
  - 1024
  - 1152
  - 1280
  - 1536
final_output_length:
  value: 312
freeze_conv_layers:
  value: true
global_acc_size:
  value: 128
gradient_clip:
  value: 5
input_length:
  value: 65536
kernel_transformation:
  value: relu_kernel_transformation
learnable_PE:
  value: true
load_init:
  value: true
log_atac:
  value: true
loss_fn:
  value: poisson
lr_base1:
  value: 5.0e-06
lr_base2:
  value: 0.0001
num_heads:
  value: 4
num_random_features:
  value: 256
num_transformer_layers:
  value: 2
optimizer:
  value: adamw
output_length:
  value: 512
output_length_ATAC:
  value: 16384
output_res:
  value: 128
pointwise_dropout_rate:
  value: 0.1
predict_masked_atac_bool:
  value: true
rectify:
  value: true
sonnet_weights_bool:
  value: true
stable_variant:
  value: false
use_atac:
  value: true
use_global_acc:
  value: true
wd_1_frac:
  value: 0.001
wd_2_frac:
  value: 0.01
